spring.application.name=EurekaServer
server.port=8761

# --- Eureka Server Config ---
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.instance.hostname=localhost

# Optional: Improve startup speed for container
logging.level.com.netflix.eureka=OFF
logging.level.com.netflix.discovery=OFF