spring.application.name=userservice
server.port=8082

# --- Database Configuration (Neon PostgreSQL) ---
# We use Env Variables here so you don't expose secrets on GitHub
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA Configuration ---
# 'update' creates tables if missing, but keeps data
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# --- Data Initialization (Critical for data.sql) ---
# Wait for Hibernate to create tables before running SQL
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.continue-on-error=true

# --- Eureka Configuration (Localhost for Docker) ---
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
# FORCE localhost so Nginx/Container can find it
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false

# --- JWT Configuration ---
jwt.secret=3p97gfbo83q7goeob873qd87*O&87dog87h78h97HO87o87g87B
jwt.expiration=86400000

# --- Mail Configuration ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true